name: 'graphql-convert-introspection-schema'
description: 'Convert an introspection schema.json to a .graphql schema'
author: 'Allex Veldman'
branding:
  icon: activity
  color: purple
inputs:
  schema:
    required: true
    description: 'path to schema.json'
  output:
    required: false
    default: './schema.graphql'
    description: 'file path to write the schema to'
outputs:
  path:
    description: 'file path of the generated schema'
runs:
  using: 'node16'
  main: 'dist/index.js'
